"use client";

import Link from "next/link";
import React, { useEffect, useState, useCallback } from "react";
import ExportButton from "@/components/ExportButton";
import { generateCultureAnalysisReport } from "@/lib/pdfGenerator";
import {
  getCultureAnalysis,
  CultureAnalysisJson,
} from "./actions";
import { getAccessToken } from "@/lib/api";

interface PageProps {
  params: Promise<{ id: string }>;
}

type AnalysisState =
  | "loading"        // Initial fetch in progress
  | "processing"     // Watcher is currently analyzing this meeting
  | "completed"      // Analysis available
  | "pending"        // Waiting for watcher to pick it up
  | "failed"         // Analysis failed
  | "no-transcript"; // Meeting has no transcript yet

// User-friendly messages for each state
const STATUS_MESSAGES: Record<AnalysisState, { title: string; description: string }> = {
  loading: {
    title: "Loading analysis...",
    description: "Checking if a culture analysis exists for this meeting.",
  },
  processing: {
    title: "Analysis in progress",
    description:
      "The culture analysis is currently being generated by the AI model. This usually takes 1–2 minutes. The page will refresh automatically.",
  },
  pending: {
    title: "Analysis queued",
    description:
      "This meeting is eligible for culture analysis and will be processed automatically shortly. The page will refresh automatically when results are ready.",
  },
  completed: {
    title: "Analysis complete",
    description: "",
  },
  failed: {
    title: "Analysis failed",
    description:
      "The culture analysis encountered an error. The system will retry automatically within 30 minutes.",
  },
  "no-transcript": {
    title: "No transcript available",
    description:
      "Culture analysis requires a meeting transcript with more than 5 utterances. Once the meeting ends and a transcript is generated, the analysis will be triggered automatically.",
  },
};

export default function CulturalAnalysisPage({ params }: PageProps) {
  const resolvedParams = React.use(params);
  const meetingId = resolvedParams.id;

  const [state, setState] = useState<AnalysisState>("loading");
  const [error, setError] = useState<string | null>(null);
  const [errorDetail, setErrorDetail] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<CultureAnalysisJson | null>(null);
  const [analyzedAt, setAnalyzedAt] = useState<string | null>(null);
  const [meetingTitle, setMeetingTitle] = useState<string | undefined>(undefined);
  const [isExporting, setIsExporting] = useState(false);

  const fetchAnalysis = useCallback(async () => {
    setError(null);
    setErrorDetail(null);
    const token = getAccessToken();
    if (!token) {
      setError("Authentication required. Please log in to view this page.");
      setState("failed");
      return;
    }

    // Server actions never throw in production — they always return a structured response.
    const response = await getCultureAnalysis(meetingId, token);

    if (!response.success) {
      const code = response.errorCode;
      if (code === "not_found") {
        setState("pending");
      } else if (code === "no_transcript") {
        setState("no-transcript");
      } else if (code === "auth_error") {
        setState("failed");
        setError("Authentication required. Please log in to view this page.");
      } else {
        setState("failed");
        setError("Unable to load culture analysis. Please try again later.");
        setErrorDetail(response.message || null);
      }
      return;
    }

    if (response.data) {
      const { status, analysis: analysisData, error_message } = response.data;

      if (status === "completed" && analysisData) {
        setAnalysis(analysisData);
        setMeetingTitle(response.data.meeting_title);
        setAnalyzedAt(response.data.analyzed_at ?? null);
        setState("completed");
      } else if (status === "processing") {
        setState("processing");
      } else if (status === "failed") {
        setState("failed");
        if (error_message) {
          setErrorDetail(error_message);
        }
      } else {
        setState("pending");
      }
    } else {
      setState("pending");
    }
  }, [meetingId]);

  // Initial fetch on mount
  useEffect(() => {
    if (meetingId) {
      fetchAnalysis();
    }
  }, [meetingId, fetchAnalysis]);

  // Auto-refresh when analysis is pending or processing
  useEffect(() => {
    if (state === "pending" || state === "processing") {
      const interval = setInterval(() => {
        fetchAnalysis();
      }, 15000); // Poll every 15 seconds

      return () => clearInterval(interval);
    }
  }, [state, fetchAnalysis]);

  const statusInfo = STATUS_MESSAGES[state];
  const hasAnalysis = state === "completed" && !!analysis;

  const handleExport = useCallback(() => {
    if (!analysis) return;

    try {
      setIsExporting(true);
      generateCultureAnalysisReport({
        meetingId,
        meetingTitle,
        analyzedAt,
        analysis,
      });
    } finally {
      setIsExporting(false);
    }
  }, [analysis, analyzedAt, meetingId, meetingTitle]);

  return (
    <div className="max-w-4xl mx-auto">
      <div className="text-sm text-gray-500 mb-6 flex items-center">
        <Link
          href="/management/meetings"
          className="hover:text-gray-900 transition-colors"
        >
          All Meetings
        </Link>
        <span className="mx-2">/</span>
        <Link
          href={`/management/meetings/${meetingId}`}
          className="hover:text-gray-900 transition-colors"
        >
          Meeting Details
        </Link>
        <span className="mx-2">/</span>
        <span className="text-gray-900 font-medium">Cultural Analysis</span>
      </div>

      <div className="flex justify-between items-center mb-8 gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            Meeting Cultural Analysis Overview
          </h1>
          <p className="text-sm text-gray-500 mt-1">
            Culture analysis is generated automatically once a meeting ends and
            a transcript is available.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <ExportButton
            onClick={handleExport}
            disabled={!hasAnalysis}
            loading={isExporting}
            label="Export PDF"
          />
        </div>
      </div>

      {/* Status banner for non-completed states */}
      {state === "loading" && (
        <div className="mb-6 flex items-center gap-3 rounded-lg border border-gray-200 bg-gray-50 px-5 py-4 text-sm text-gray-600">
          <div className="h-4 w-4 animate-spin rounded-full border-2 border-indigo-600 border-t-transparent shrink-0" />
          <div>
            <p className="font-medium text-gray-800">{statusInfo.title}</p>
            <p className="mt-0.5">{statusInfo.description}</p>
          </div>
        </div>
      )}

      {state === "processing" && (
        <div className="mb-6 flex items-center gap-3 rounded-lg border border-indigo-200 bg-indigo-50 px-5 py-4 text-sm text-indigo-700">
          <div className="h-4 w-4 animate-spin rounded-full border-2 border-indigo-600 border-t-transparent shrink-0" />
          <div>
            <p className="font-medium">{statusInfo.title}</p>
            <p className="mt-0.5 text-indigo-600">{statusInfo.description}</p>
          </div>
        </div>
      )}

      {state === "pending" && (
        <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-800">
          <div className="flex items-center gap-2">
            <svg className="h-5 w-5 shrink-0 text-amber-500" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            </svg>
            <p className="font-medium">{statusInfo.title}</p>
          </div>
          <p className="mt-1 ml-7 text-amber-700">{statusInfo.description}</p>
        </div>
      )}

      {state === "no-transcript" && (
        <div className="mb-6 rounded-lg border border-gray-200 bg-gray-50 px-5 py-4 text-sm text-gray-600">
          <div className="flex items-center gap-2">
            <svg className="h-5 w-5 shrink-0 text-gray-400" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
            </svg>
            <p className="font-medium text-gray-800">{statusInfo.title}</p>
          </div>
          <p className="mt-1 ml-7">{statusInfo.description}</p>
        </div>
      )}

      {/* Error display */}
      {(state === "failed" || error) && (
        <div className="mb-6 rounded-lg border border-red-200 bg-red-50 px-5 py-4 text-sm">
          <div className="flex items-center gap-2 text-red-800">
            <svg className="h-5 w-5 shrink-0 text-red-500" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
            </svg>
            <p className="font-medium">
              {error || statusInfo.title}
            </p>
          </div>
          <p className="mt-1 ml-7 text-red-700">
            {errorDetail || statusInfo.description}
          </p>
        </div>
      )}

      {/* Completed analysis timestamp */}
      {hasAnalysis && analyzedAt && (
        <p className="text-xs text-gray-400 mb-6">
          Analyzed on{" "}
          {new Date(analyzedAt).toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
            hour: "2-digit",
            minute: "2-digit",
          })}
        </p>
      )}

      {/* Analysis content */}
      {hasAnalysis && (
        <div className="space-y-8 text-gray-700">
          {analysis?.meeting_summary && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Meeting Summary
              </h2>
              <p className="leading-relaxed">{analysis.meeting_summary}</p>
            </section>
          )}

          {analysis?.cultural_strengths && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Cultural Strengths
              </h2>
              <ul className="list-disc list-inside space-y-1 leading-relaxed">
                {analysis.cultural_strengths.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </section>
          )}

          {analysis?.cultural_risks && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Cultural Risks
              </h2>
              <ul className="list-disc list-inside space-y-1 leading-relaxed">
                {analysis.cultural_risks.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </section>
          )}

          {analysis?.core_cultural_problem && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Core Cultural Problem
              </h2>
              <p className="leading-relaxed">
                {analysis.core_cultural_problem}
              </p>
            </section>
          )}

          {analysis?.core_problem_evidence && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Core Cultural Evidence
              </h2>
              <ul className="list-disc list-inside space-y-1 leading-relaxed">
                {analysis.core_problem_evidence.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </section>
          )}

          {analysis?.problem_chain_explanation && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Problem Chain Explanation
              </h2>
              <p className="leading-relaxed">
                {analysis.problem_chain_explanation}
              </p>
            </section>
          )}

          {analysis?.recommendations_for_management && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Recommendations for Management
              </h2>
              <ul className="list-disc list-inside space-y-1 leading-relaxed">
                {analysis.recommendations_for_management.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </section>
          )}

          {analysis?.evidence_notes && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Evidence Notes
              </h2>
              <ul className="list-disc list-inside space-y-1 leading-relaxed">
                {analysis.evidence_notes.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </section>
          )}

          {analysis?.limitations && (
            <section>
              <h2 className="text-base font-bold text-gray-900 mb-2">
                Limitations
              </h2>
              <p className="leading-relaxed">{analysis.limitations}</p>
            </section>
          )}
        </div>
      )}
    </div>
  );
}
